// Synthetic, reusable content. Integers are USD cents for this prototype only.
export const event = {
  name: 'Holiday Trade Show', host: 'Northline Business Exchange',
  date: 'December 12', closes: '6:00 PM', timezone: 'Pacific',
  business: 'Juniper Studio', participant: 'Jamie Chen', increment: 2500,
};
export const lots = [
  { id: 'cabin', number: '01', title: 'A little cabin. A whole weekend away.',
    short: 'Two nights at Cedar & Pine', category: 'Getaways', sponsor: 'Cedar & Pine Retreats', logo: 'cedar',
    image: 'cabin', alt: 'A timber cabin tucked into a quiet evergreen forest',
    current: 32500, count: 8, leader: 'Hearth & Home Design', person: 'Morgan Ellis',
    description: 'Trade the inbox for the evergreens. Settle into a private woodland cabin for two nights, with a wood-burning stove, a breakfast basket, and miles of trails right outside your door.',
    includes: ['Two nights for two guests', 'Locally made breakfast basket', 'Friday–Sunday stays included'],
    fine: 'Fictional package: dates arranged with Cedar & Pine; holiday weekends excluded. Travel is not included.',
    history: [{ business: 'Hearth & Home Design', person: 'Morgan Ellis', amount: 32500, time: '2:41 PM' }, { business: 'Copper Kettle Café', person: 'Avery Brooks', amount: 30000, time: '2:36 PM' }, { business: 'Westward Print & Packaging', person: 'Sam Rivera', amount: 27500, time: '2:28 PM' }] },
  { id: 'coffee', number: '02', title: 'Better mornings for the whole office',
    short: 'Six months of small-batch coffee', category: 'For the team', sponsor: 'Common Ground Coffee', logo: 'coffee',
    image: 'coffee', alt: 'Freshly brewed coffee and roasted beans on a café table',
    current: 15000, count: 5, leader: 'Westward Print & Packaging', person: 'Sam Rivera',
    description: 'The meeting everyone will actually look forward to. A rotating selection of freshly roasted coffee, delivered to your workplace every month for six months, plus a guided tasting for your team.',
    includes: ['Four 12 oz bags each month for six months', 'One tasting for up to eight people', 'Local delivery included'],
    fine: 'Fictional package: local delivery area and timing to be arranged with Common Ground.',
    history: [{ business: 'Westward Print & Packaging', person: 'Sam Rivera', amount: 15000, time: '2:39 PM' }, { business: 'Goodform Architecture', person: 'Riley Park', amount: 12500, time: '2:31 PM' }] },
  { id: 'dinner', number: '03', title: 'An evening at the chef’s table, for six',
    short: 'Five courses, very good company', category: 'Food & drink', sponsor: 'The Long Table', logo: 'table',
    image: 'dinner', alt: 'An elegantly set restaurant table under warm light',
    current: 45000, count: 12, leader: 'Copper Kettle Café', person: 'Avery Brooks',
    description: 'Bring your favorite people to the table. Chef Elena builds a five-course seasonal menu around the best of the region, with a little story behind every plate.',
    includes: ['Private chef’s table for six', 'Five-course seasonal menu', 'Non-alcoholic pairing included'],
    fine: 'Fictional package: advance booking required. Dietary requirements discussed when reserving.',
    history: [{ business: 'Copper Kettle Café', person: 'Avery Brooks', amount: 45000, time: '2:40 PM' }, { business: 'Hearth & Home Design', person: 'Morgan Ellis', amount: 42500, time: '2:32 PM' }] },
  { id: 'ceramics', number: '04', title: 'Made by hand, made for your everyday',
    short: 'A collection of six studio ceramics', category: 'Good things', sponsor: 'Soft Earth Studio', logo: 'earth',
    image: 'ceramics', alt: 'Handmade ceramic vessels in soft earthy glazes',
    current: 10000, count: 3, leader: 'Goodform Architecture', person: 'Riley Park',
    description: 'Six wonderfully imperfect pieces for the rituals that make a day: morning coffee, a shared meal, flowers from the garden. Each piece is thrown and glazed by hand in the Soft Earth workshop.',
    includes: ['Two mugs, two bowls, and two serving pieces', 'Handmade stoneware', 'Gift packaging'],
    fine: 'Fictional package: finish and dimensions vary because each piece is handmade. Collection arranged with the studio.',
    history: [{ business: 'Goodform Architecture', person: 'Riley Park', amount: 10000, time: '2:38 PM' }, { business: 'Copper Kettle Café', person: 'Avery Brooks', amount: 7500, time: '2:19 PM' }] },
  { id: 'bicycle', number: '05', title: 'The scenic route starts here',
    short: 'A city bicycle, fitted just for you', category: 'Good things', sponsor: 'Spoke & Co.', logo: 'spoke',
    image: 'bicycle', alt: 'A classic city bicycle ready for a leisurely ride',
    current: 27500, count: 7, leader: 'Hearth & Home Design', person: 'Morgan Ellis',
    description: 'Meet your new excuse to take the long way home. A comfortable city bicycle with a personalized fitting, a helmet, and a first service from the friendly team at Spoke & Co.',
    includes: ['One city bicycle', 'Individual fitting and helmet', 'First service within six months'],
    fine: 'Fictional package: available frame sizes and colors confirmed at fitting. No cash alternative assumed.',
    history: [{ business: 'Hearth & Home Design', person: 'Morgan Ellis', amount: 27500, time: '2:37 PM' }, { business: 'Westward Print & Packaging', person: 'Sam Rivera', amount: 25000, time: '2:21 PM' }] },
  { id: 'flowers', number: '06', title: 'Fresh flowers, every month for a year',
    short: 'A little seasonality for your space', category: 'For the team', sponsor: 'Fieldwork Floral', logo: 'floral',
    image: 'flowers', alt: 'A loose arrangement of pink and white seasonal flowers',
    current: 22500, count: 6, leader: 'Westward Print & Packaging', person: 'Sam Rivera',
    description: 'A year of small, beautiful arrivals. Fieldwork will put together a generous seasonal arrangement each month for your front desk, meeting room, or favorite corner.',
    includes: ['Twelve seasonal arrangements', 'A reusable ceramic vase with the first delivery', 'One local delivery each month'],
    fine: 'Fictional package: begins in January. Flowers change with the season; pictured arrangement is illustrative.',
    history: [{ business: 'Westward Print & Packaging', person: 'Sam Rivera', amount: 22500, time: '2:35 PM' }, { business: 'Goodform Architecture', person: 'Riley Park', amount: 20000, time: '2:27 PM' }] },
];
